image:
  repository: grommunio/gromox-core
  tag: 0.3-opensuse-leap-15-4

deployment:
  replicas: 1

config:
  fqdn: example.com

mariadb:
  enabled: true
  auth:
    database: grommunio
    username: grommunio
