apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: db-service
  MARIADB_USER: grommunio
  MARIADB_PASSWORD: my_cool_secret 
  MARIADB_ROOT_PASSWORD: my-secret-pw
  MARIADB_DATABASE: grommunio
