apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-links
  namespace: {{ .Release.Namespace }}
data:
  config.sh: |
    cat > /etc/grommunio-admin-common/config.json<<EOCONF
      {
          "mailWebAddress": "https://${FQDN}/web",
          "chatWebAddress": "https://${FQDN}/chat",
          "videoWebAddress": "https://${FQDN}/meet",
          "fileWebAddress": "https://${FQDN}/files",
          "archiveWebAddress": "https://${FQDN}/archive"
      }
    EOCONF
  web-config.conf: |
    location /config.json {
      alias /etc/grommunio-admin-common/config.json;
    }
