apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-plugins
  namespace: {{ .Release.Namespace }}
data:
  conf.yaml: |
    sync:
      connection:
        host: http://grommunio-core:6379
    options:
        antispamUrl: http://grommunio-core:11334
