{{- if .Values.core.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-core
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    {{- if .Values.core.ingress.annotations }}
    {{- toYaml .Values.core.ingress.annotations | nindent 6 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.core.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-core
                port:
                  number: 443
{{- end }}
