{{- if .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  annotations:
    {{- toYaml .Values.admin.ingress.annotations | nindent 6 }}
spec:
  rules:
    - host: {{ .Values.admin.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port:
                  number: 443
{{- end }}
