apiVersion: v1
kind: Service
metadata:
    name: { { .Release.Name } }-admin
    namespace: { { .Release.Namespace } }
spec:
    selector:
        app: { { .Release.Name } }-admin
    ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 8443
