apiVersion: v1
kind: Service
metadata:
    name: { { .Release.Name } }-core
    namespace: { { .Release.Namespace } }
spec:
    selector:
        app: { { .Release.Name } }-core
    ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
        - name: redis
          protocol: TCP
          port: 6379
          targetPort: 6379
        - name: rspamd
          protocol: TCP
          port: 11334
          targetPort: 11334
