apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.config.fqdn }}
  secretName: {{ .Release.Name }}-cert-tls
  issuerRef:
    name: {{ .Release.Name }}-selfsigned
